# Generated by Django 3.0.8 on 2020-07-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline1', '0004_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='airline1',
            field=models.ManyToManyField(blank=True, related_name='passengers', to='airline1.Flight'),
        ),
    ]
