# Generated by Django 3.0.8 on 2020-07-16 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=64)),
                ('LastName', models.CharField(max_length=64)),
                ('Email', models.CharField(max_length=64)),
                ('Gender', models.CharField(max_length=20)),
                ('Comment', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=40)),
                ('app', models.ManyToManyField(blank=True, related_name='User', to='app.Website')),
            ],
        ),
    ]
