# Generated by Django 3.0.8 on 2020-08-09 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_subscribe0'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
